services:
  aplicativo_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: docker_poo_dev # nome do contÃªiner
    restart: unless-stopped
    ports:
      - "8988:8988"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.dev
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
      - ./logs:/app/logs